driver:
  name: dokken
  # required to test systemd services
  # https://kitchen.ci/docs/drivers/dokken/#privileged
  privileged: true

  chef_version: 18.1.0

transport:
  name: dokken

provisioner:
  name: dokken #chef_zero
  chef_license: accept-no-persist
  encrypted_data_bag_secret_key_path: example_secretkey

verifier:
  name: inspec

platforms:
  - name: ubuntu
    driver:
      image: dokken/ubuntu-20.04
      pid_one_command: /bin/systemd
  - name: debian
    driver:
      image: dokken/debian-11
      pid_one_command: /bin/systemd

# todo: add more test platforms
# dokken/ubuntu-18.04
# dokken/ubuntu-22.10
# dokken/ubuntu-22.10
# dokken/debian-12
# dokken/debian-11
# dokken/debian-10

suites:
  - name: default
    run_list:
      - role[mongodb]
      - role[errbit]
    attributes:

