driver:
  name: dokken
  chef_version: 18.1.0

transport:
  name: dokken

provisioner:
  name: dokken #chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04
    driver:
      image: dokken/ubuntu-20.04

suites:
  - name: default
    run_list:
      - role[base]
    attributes:

